// export enum SPELL_TYPE_ID {
// 	PUNCH = 'PUNCH',
// 	FIREBALL = 'FIREBALL',
// 	BURN_TICK = 'BURN_TICK',
// 	SCAR = 'SCAR',
// 	HEAL = 'HEAL',
// 	LIFE_TAP = 'LIFE_TAP',
// 	CLEASE_DISEASE = 'CLEASE_DISEASE',
// 	BOMB = 'BOMB',
// 	EXPLOSION = 'EXPLOSION',
// }
