import {
	AURA_DIRECTION_TYPE_ID,
	AURA_TYPE_ID,
	DISPEL_TYPE_ID,
	RESOURCE_TYPE_ID,
	SCHOOL_TYPE_ID,
	SPELL_EFFECT_TYPE_ID,
	SpellModel,
} from '@/lib/spell/spell-models';
import { STAT_TYPE_ID } from '@/lib/character/character-models';

export enum SPELL_TYPE_ID {
	FIREBALL = 'FIREBALL',
	PUNCH = 'PUNCH',
	LESSER_HEAL = 'LESSER_HEAL',
	DMG_BOOST = 'DMG_BOOST',
	DMG_REDUCTION = 'DMG_REDUCTION',
	DMG_PERCENT_UP = 'DMG_PERCENT_UP',
	DMG_PERCENT_DOWN = 'DMG_PERCENT_DOWN',
	DMG_MULTIPLIED_UP = 'DMG_MULTIPLIED_UP',
	DMG_MULTIPLIED_DOWN = 'DMG_MULTIPLIED_DOWN',
	SHIELD = 'SHIELD',
	SHIELD_PERCENT = 'SHIELD_PERCENT',
	SHIELD_MULTIPLIER = 'SHIELD_MULTIPLIER',
	HOT = 'HOT',
	HEAL_BOOST = 'HEAL_BOOST',
	HEAL_PERCENT_UP = 'HEAL_PERCENT_UP',
	HEAL_MULTIPLIED_UP = 'HEAL_MULTIPLIED_UP',
}

export const spellData: Record<SPELL_TYPE_ID, SpellModel> = {
	[SPELL_TYPE_ID.FIREBALL]: {
		spellTypeId: SPELL_TYPE_ID.FIREBALL,
		title: 'Fireball',
		description: 'Hurls a fiery ball that causes %{} %{} damage and an additional ${} ${} damage over ${} sec.',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 30,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 1500,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 4000,
		schoolTypeId: SCHOOL_TYPE_ID.FIRE,
		dispelTypeId: DISPEL_TYPE_ID.NONE,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.SCHOOL_DAMAGE,
				schoolTypeId: SCHOOL_TYPE_ID.FIRE,
				value: 10,
				valueModifiers: [{ stat: STAT_TYPE_ID.SPELL_POWER, coefficient: 0 }],
			},
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.PERIODIC_DAMAGE,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.NONE,
				value: 1,
				valueModifiers: [{ stat: STAT_TYPE_ID.SPELL_POWER, coefficient: 0 }],
				intervalInMs: 2000,
			},
		],
	},
	[SPELL_TYPE_ID.PUNCH]: {
		spellTypeId: SPELL_TYPE_ID.PUNCH,
		title: 'Punch',
		description: 'Punch the target.',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 10,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 0,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 0,
		schoolTypeId: SCHOOL_TYPE_ID.PHYSICAL,
		dispelTypeId: DISPEL_TYPE_ID.NONE,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.SCHOOL_DAMAGE,
				schoolTypeId: SCHOOL_TYPE_ID.PHYSICAL,
				value: 10,
				valueModifiers: [],
			},
		],
	},
	[SPELL_TYPE_ID.LESSER_HEAL]: {
		spellTypeId: SPELL_TYPE_ID.LESSER_HEAL,
		title: 'Lesser Heal',
		description: 'heal the target.',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 10,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 0,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 0,
		schoolTypeId: SCHOOL_TYPE_ID.HOLY,
		dispelTypeId: DISPEL_TYPE_ID.NONE,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.HEAL,
				value: 10,
				valueModifiers: [],
			},
		],
	},
	[SPELL_TYPE_ID.DMG_BOOST]: {
		spellTypeId: SPELL_TYPE_ID.DMG_BOOST,
		title: 'o.Dmg +10',
		description: 'Increase outgoing damage by 10.',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 10,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 0,
		cooldownDurationInMs: 8000,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 8000,
		schoolTypeId: SCHOOL_TYPE_ID.ARCANE,
		dispelTypeId: DISPEL_TYPE_ID.MAGIC,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.MODIFY_DAMAGE_FLAT,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.OUTGOING,
				intervalInMs: 0,
				value: 10,
				valueModifiers: [],
			},
		],
	},
	[SPELL_TYPE_ID.DMG_REDUCTION]: {
		spellTypeId: SPELL_TYPE_ID.DMG_REDUCTION,
		title: 'o.Dmg -10',
		description: 'Decrease outgoing damage by 10.',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 10,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 0,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 20000,
		schoolTypeId: SCHOOL_TYPE_ID.ARCANE,
		dispelTypeId: DISPEL_TYPE_ID.MAGIC,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.MODIFY_DAMAGE_FLAT,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.OUTGOING,
				intervalInMs: 0,
				value: -10,
				valueModifiers: [],
			},
		],
	},
	[SPELL_TYPE_ID.DMG_PERCENT_UP]: {
		spellTypeId: SPELL_TYPE_ID.DMG_PERCENT_UP,
		title: 'o.Dmg +10%',
		description: 'Increase outgoing damage by 10%.',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 10,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 0,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 20000,
		schoolTypeId: SCHOOL_TYPE_ID.ARCANE,
		dispelTypeId: DISPEL_TYPE_ID.MAGIC,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.MODIFY_DAMAGE_PERCENT,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.OUTGOING,
				intervalInMs: 0,
				value: 0.1,
				valueModifiers: [],
			},
		],
	},
	[SPELL_TYPE_ID.DMG_PERCENT_DOWN]: {
		spellTypeId: SPELL_TYPE_ID.DMG_PERCENT_DOWN,
		title: 'o.Dmg -10%',
		description: 'Decrease outgoing damage by 10%.',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 10,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 0,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 20000,
		schoolTypeId: SCHOOL_TYPE_ID.ARCANE,
		dispelTypeId: DISPEL_TYPE_ID.MAGIC,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.MODIFY_DAMAGE_PERCENT,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.OUTGOING,
				intervalInMs: 0,
				value: -0.1,
				valueModifiers: [],
			},
		],
	},
	[SPELL_TYPE_ID.DMG_MULTIPLIED_UP]: {
		spellTypeId: SPELL_TYPE_ID.DMG_MULTIPLIED_UP,
		title: 'o.Dmg *2',
		description: 'Double outgoing damage',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 10,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 0,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 20000,
		schoolTypeId: SCHOOL_TYPE_ID.ARCANE,
		dispelTypeId: DISPEL_TYPE_ID.MAGIC,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.MODIFY_DAMAGE_MULTIPLIER,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.OUTGOING,
				intervalInMs: 0,
				value: 2,
				valueModifiers: [],
			},
		],
	},
	[SPELL_TYPE_ID.DMG_MULTIPLIED_DOWN]: {
		spellTypeId: SPELL_TYPE_ID.DMG_MULTIPLIED_DOWN,
		title: 'o.Dmg *0.5',
		description: 'Halve outgoing damage',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 10,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 0,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 20000,
		schoolTypeId: SCHOOL_TYPE_ID.ARCANE,
		dispelTypeId: DISPEL_TYPE_ID.MAGIC,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.MODIFY_DAMAGE_MULTIPLIER,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.OUTGOING,
				intervalInMs: 0,
				value: 0.5,
				valueModifiers: [],
			},
		],
	},
	[SPELL_TYPE_ID.SHIELD]: {
		spellTypeId: SPELL_TYPE_ID.SHIELD,
		title: 'i.Dmg -5',
		description: 'Reduce incoming damage by 5',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 10,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 0,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 20000,
		schoolTypeId: SCHOOL_TYPE_ID.PHYSICAL,
		dispelTypeId: DISPEL_TYPE_ID.NONE,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.MODIFY_DAMAGE_FLAT,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.INCOMING,
				intervalInMs: 0,
				value: -5,
				valueModifiers: [],
			},
		],
	},
	[SPELL_TYPE_ID.SHIELD_PERCENT]: {
		spellTypeId: SPELL_TYPE_ID.SHIELD_PERCENT,
		title: 'i.Dmg -10%',
		description: 'Reduce incoming damage by 10%',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 10,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 0,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 20000,
		schoolTypeId: SCHOOL_TYPE_ID.PHYSICAL,
		dispelTypeId: DISPEL_TYPE_ID.NONE,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.MODIFY_DAMAGE_PERCENT,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.INCOMING,
				intervalInMs: 0,
				value: -0.1,
				valueModifiers: [],
			},
		],
	},
	[SPELL_TYPE_ID.SHIELD_MULTIPLIER]: {
		spellTypeId: SPELL_TYPE_ID.SHIELD_MULTIPLIER,
		title: 'i.Dmg *0.5',
		description: 'Reduce incoming damage by qart',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 10,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 0,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 20000,
		schoolTypeId: SCHOOL_TYPE_ID.PHYSICAL,
		dispelTypeId: DISPEL_TYPE_ID.NONE,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.MODIFY_DAMAGE_MULTIPLIER,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.INCOMING,
				intervalInMs: 0,
				value: 0.5,
				valueModifiers: [],
			},
		],
	},
	[SPELL_TYPE_ID.HOT]: {
		spellTypeId: SPELL_TYPE_ID.HOT,
		title: 'HoT 1',
		description: 'Heals over time.',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 30,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 1500,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 20000,
		schoolTypeId: SCHOOL_TYPE_ID.HOLY,
		dispelTypeId: DISPEL_TYPE_ID.MAGIC,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.PERIODIC_HEAL,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.NONE,
				value: 1,
				valueModifiers: [{ stat: STAT_TYPE_ID.SPELL_POWER, coefficient: 0 }],
				intervalInMs: 2000,
			},
		],
	},
	[SPELL_TYPE_ID.HEAL_BOOST]: {
		spellTypeId: SPELL_TYPE_ID.HEAL_BOOST,
		title: 'o.Heal +10',
		description: 'Increases healing done by 10.',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 30,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 1500,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 20000,
		schoolTypeId: SCHOOL_TYPE_ID.HOLY,
		dispelTypeId: DISPEL_TYPE_ID.MAGIC,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.MODIFY_HEALING_FLAT,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.OUTGOING,
				value: 10,
				valueModifiers: [],
				intervalInMs: 0,
			},
		],
	},
	[SPELL_TYPE_ID.HEAL_PERCENT_UP]: {
		spellTypeId: SPELL_TYPE_ID.HEAL_PERCENT_UP,
		title: 'o.Heal +10%',
		description: 'Increases healing done by 10%.',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 30,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 1500,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 20000,
		schoolTypeId: SCHOOL_TYPE_ID.HOLY,
		dispelTypeId: DISPEL_TYPE_ID.MAGIC,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.MODIFY_HEALING_PERCENT,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.OUTGOING,
				value: 0.1,
				valueModifiers: [],
				intervalInMs: 0,
			},
		],
	},
	[SPELL_TYPE_ID.HEAL_MULTIPLIED_UP]: {
		spellTypeId: SPELL_TYPE_ID.HEAL_MULTIPLIED_UP,
		title: 'o.Heal *2',
		description: 'Increases healing done by 2x.',
		cost: [
			{
				resourceTypeId: RESOURCE_TYPE_ID.MANA,
				amountFlat: 30,
				amountPercent: 0,
			},
		],
		castTimeDurationInMs: 0,
		cooldownDurationInMs: 0,
		globalCooldownDurationInMs: 1500,
		auraDurationInMs: 20000,
		schoolTypeId: SCHOOL_TYPE_ID.HOLY,
		dispelTypeId: DISPEL_TYPE_ID.MAGIC,
		spellEffects: [
			{
				spellEffectTypeId: SPELL_EFFECT_TYPE_ID.APPLY_AURA,
				auraTypeId: AURA_TYPE_ID.MODIFY_HEALING_MULTIPLIER,
				auraDirectionTypeId: AURA_DIRECTION_TYPE_ID.OUTGOING,
				value: 2,
				valueModifiers: [],
				intervalInMs: 0,
			},
		],
	},
};
