export enum SPELL_TYPE_ID {
	PUNCH = 'PUNCH',
	HEAL = 'HEAL',
	FIREBALL = 'FIREBALL',
	RENEW = 'RENEW',
	DISPEL_MAGIC = 'DISPEL_MAGIC',
	VIT_UP = 'VIT_UP',
	HASTE_UP = 'HASTE_UP',
	INTERRUPT = 'INTERRUPT',
	HEALTH_POTION = 'HEALTH_POTION',
	MANA_POTION = 'MANA_POTION',

	ROT_PUT = 'ROT_PUT',

	SUMMON_MARROWHOUND = 'SUMMON_MARROWHOUND',
	BITE = 'BITE',
	REND = 'REND',
}
